Issue #1531 - Pagination to be implemented in all widgets - For better user experience
Azure/api-management-developer-portal pull request #1544
Opened 2021-11-24 09:56 UTC by Varun270489

implemented pagination in api-list & product-list widget

2021-12-06 18:53 UTC, azaslonov requested changes

2021-12-06 18:53 UTC, azaslonov commented on src/components/apis/list-of-apis/ko/runtime/api-list.html
> +<style>
Could you please move this <style> block content to [pagination.scss](https://github.com/Azure/api-management-developer-portal/blob/master/src/themes/website/styles/pagination.scss) file and see how existing styles can be married with yours?

2021-12-06 18:53 UTC, azaslonov commented on src/components/apis/list-of-apis/ko/runtime/api-list.html
>      <!-- ko if: hasPager -->
`<!-- ko if: hasPager -->` and `data-bind="visible: needPaging"` seem like solving the same problem. Probably having `<!-- ko if: needPaging -->` on top level would be enough.

2021-12-06 18:53 UTC, azaslonov commented on src/components/apis/list-of-apis/ko/runtime/api-list.ts
> +     public pageCount() {
`public pageCount() {` - Please add return types to every function.

2021-12-06 18:53 UTC, azaslonov commented on src/components/apis/list-of-apis/ko/runtime/api-list.ts
> +     //-----pagination changes start ----------------------------
`//-----pagination changes start ----------------------------` - Please remove.

2021-12-06 18:53 UTC, azaslonov commented on src/components/apis/list-of-apis/ko/runtime/api-list.ts
> +    //------pagination changes end ---------------------------
`//------pagination changes end ---------------------------` - Please remove this comment

2021-12-06 18:53 UTC, azaslonov commented on src/components/products/product-list/ko/runtime/product-list.html
> +<style>
Same as previous comment - please move this `<style>` tag content to designated file.

2021-12-06 18:53 UTC, azaslonov commented on src/components/products/product-list/ko/runtime/product-list.ts
> +        this.totalNoOfItems = ko.observable();  //pagination changes
Please remove the comment `//pagination changes`

2021-12-06 18:53 UTC, azaslonov commented on src/components/products/product-list/ko/runtime/product-list.ts
> +    public totalNoOfItems: ko.Observable<number>;   //pagination changes
Please remove the comment `//pagination changes`

2021-12-06 18:53 UTC, azaslonov commented on src/components/products/product-list/ko/runtime/product-list.ts
> +     //-----pagination changes start ----------------------------
Please remove the comment `//-----pagination changes start ----------------------------`

2021-12-06 18:53 UTC, azaslonov commented on src/services/apiService.ts
> +        page.count =pageOfApiTagResources.count;
`page.count =pageOfApiTagResources.count` - please use Shift+Alt+F for code formatting.

2021-12-07 06:34 UTC, Varun270489 commented
all review comments implemented

2021-12-08 22:18 UTC, azaslonov commented
@Varun270489, considering you created another pull request, do we still need this one?

2021-12-16 06:12 UTC, Varun270489 commented
this is the only pull request

2021-12-17 18:47 UTC, azaslonov approved these changes

2021-12-17 18:48 UTC, merged