Error state of non-existent API and Readability of subscription key
Azure/api-management-developer-portal pull request #977
Opened 2020-10-19 09:13 UTC by hakashya

Fixed the error state of the non-existent (Issue #972). The error message when accessing a deleted or non existent API looks as follows:
![image](https://user-images.githubusercontent.com/58763328/96423390-e5dd5400-1216-11eb-9dd0-1dbba4ce0c48.png)

Also modified the name of the subscription key that is used in Try It, referenced in Issue #945. Changed the format from "Primary-191f" to "Primary-SubName".
![image](https://user-images.githubusercontent.com/58763328/96424527-6fd9ec80-1218-11eb-84f4-a7df019946a0.png)

2020-10-19 18:01 UTC, mikebudzynski requested changes
Thank you for the contribution, it's much appreciated! I left a few minor comments, could you please address them?

2020-10-20 00:50 UTC, mikebudzynski commented on src/components/operations/operation-details/ko/runtime/operation-console.ts
> +                    name: `Primary-${subscription.name}`,
@azaslonov I assume this is displayName?

2020-10-20 01:06 UTC, azaslonov commented on src/components/operations/operation-details/ko/runtime/operation-console.ts
> +                    name: `Primary-${subscription.name}`,
This is a subscription model (not MAPI contract) and "name" gets filled with "displayName" from the contract. So, it's correct.

2020-10-20 06:41 UTC, hakashya commented on src/components/apis/details-of-api/ko/runtime/api-details.html
> +        <p>No such API available</p>
I have changed the text to 

> The specified API does not exist.

2020-10-20 06:43 UTC, hakashya commented
Thank you for the review! 
I've incorporated the changes. The Try It console looks as follows:
![image](https://user-images.githubusercontent.com/58763328/96549804-9d34a200-12cd-11eb-861a-d8d5681cb489.png)

2020-10-20 17:19 UTC, mikebudzynski approved these changes

2020-10-20 23:07 UTC, azaslonov approved these changes
Thanks for your contribution, Harsha! We greatly appreciate it.

2020-10-20 23:08 UTC, merged